### ISSUE TITLE
Better example in README

### ISSUE THREAD

**Issue by judgej** [proj4php/proj4php#12]
I've realised for a while that the example in the `readme` does not actually do a transform, but I have no idea if it is a mistake in the way the example works, or a bug in the library. The "non-transforming points" is the result I get from running the example.

It's been pointed out to me by Jöran Benker, so it's probably time to raise it as a ticket:

// Source: 2.3557811127971 48.831938054369 in L93
// Conversion: 2.3557811127971 48.831938054369 in WGS84 These values are not transformed.

The [testproj.php](https://github.com/proj4php/proj4php/blob/master/test/testproj.php) script seems to do a bunch of transforms okay, so should some of the tests in there be pulled in as examples for the front page? This is probably better done by someone using the package now, who may also be able to spot whether the transforms are correctly being calculated or not.

**Comment by julien2512** [comment]
That's right, it's a mistake.

Are you talking about integration tests ? I never heard about free integration test server. Do you know any ?

**Comment by judgej** [comment]
No, not integration tests. It was just that script in the `tests` folder that might contain some better examples that can be copied to the `README` file, since all those examples in the tests folder work and do *something*.

There are free services for running unit tests for open source projects. [Travis CI](https://travis-ci.org/) is one I use on a few projects. I'm no expert on setting up and writing unit tests though - it's a whole world of tech to understand.

**Comment by julien2512** [comment]
Yes, I am aware there is a lack of samples in the README file.
The sample is correct right now.

We will add more samples along with fixing the other issues !

**Comment by julien2512** [comment]
Finally, I get it !
It was the well know change of the source point.
The README is now correct, even though it seems ugly.

I am looking on travis in order to set integration tests for the project.

**Comment by julien2512** [comment]
Ok, travis is fine, I think it is working.

Every Class in the test directory will now be run as a phpunit test on every push request.
The "branch" page let us know the branch status for these tests.

I just need to change README to reflect these change, then I think I will be able to close your issue !

**Comment by julien2512** [comment]
done
