### ISSUE TITLE
Mercator Auxiliary Sphere

### ISSUE THREAD

**Issue by plasmatronic** [proj4php/proj4php#132]
Hi, I am getting the error: 'Undefined Projection: Mercator_Auxiliary_Sphere' - any advice on fixing this and/or is this projection not currently supported? Thank you

**Comment by nickolanack** [comment]
please try that and let me know if that works...  (or even better PR if it works)

**Comment by plasmatronic** [comment]
Thanks, close but not quite, that projects the right-looking shapes, but in the wrong location. This is outside my area of expertise! below is projection file in case it enlightens. Thanks for any assistance

PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere", GEOGCS["GCS_WGS_1984", DATUM["D_WGS_1984", SPHEROID["WGS_1984", 6378137, 298.257223563]], PRIMEM["Greenwich", 0], UNIT["Degree", 0.0174532925199433]], PROJECTION["Mercator_Auxiliary_Sphere"], PARAMETER["False_Easting", 0], PARAMETER["False_Northing", 0], PARAMETER["Central_Meridian", 0], PARAMETER["Standard_Parallel_1", 0], PARAMETER["Auxiliary_Sphere_Type", 0], UNIT["Meter", 1]]

**Comment by nickolanack** [comment]
can you provide a shape file? hopefully something that is not sensitive data

**Comment by plasmatronic** [comment]
[Export (1).zip](https://github.com/proj4php/proj4php/files/11596109/Export.1.zip)

Not sensitive, please find attached an example. Thank you

**Comment by nickolanack** [comment]
I also added a check for the sphere type:

https://github.com/proj4php/proj4php/blob/17f2a5eea4f587f46ad7d0c62a4855d6b734ac69/src/Wkt.php#L218C3-L219
```php

case 'auxiliary_sphere_type':
      $wktParams->sphere=true;
break;
```

https://github.com/proj4php/proj4php/blob/17f2a5eea4f587f46ad7d0c62a4855d6b734ac69/src/Wkt.php#L511
```
self::$wktProjections["Mercator_Auxiliary_Sphere"] = "merc";
```

@plasmatronic  Let me know if that looks correct, If so I'll test and submit a PR 

<img width="701" alt="Screenshot 2023-06-08 at 11 18 46 AM" src="https://github.com/proj4php/proj4php/assets/8965209/0d1005c6-1bf0-44ed-8db6-608f9457fb19">

**Comment by plasmatronic** [comment]
Yes, that worked and I tested on a couple of other examples too. Thank you

**Comment by nickolanack** [comment]
great, I'll push the changes to the repo and then close this issue.
