### ISSUE TITLE
[CRITICAL BUG] Web service spatialreference.org has been updated and is not working anymore

### ISSUE THREAD

**Issue by JoolsMcFly** [proj4php/proj4php#136]
spatialreference.org URL for definitions used to be formatted like so

https://spatialreference.org/ref/epsg/3942/proj4/

but it's been changed to
https://spatialreference.org/ref/epsg/3942/proj4.txt

I'll add a PR to fix this.

**Comment by hkirsman** [comment]
I think I'm getting the same issue but in my case it's https://spatialreference.org/ref/epsg/3301/proj4/ that is giving 404.

**Comment by JoolsMcFly** [comment]
Yes, we're experiencing the same issue.
Adding .txt fixes the problem.

Until the PR is accepted I added this to our deploy script after `composer install`:
`sed -ri "s|/proj4/|/proj4.txt|g" vendor/proj4php/proj4php/src/Proj.php`

Yes, it's a hack but it's temporary! :)

**Comment by nickolanack** [comment]
@JoolsMcFly Thank you!!!

**Comment by JoolsMcFly** [comment]
@nickolanack glad I could help!
