### ISSUE TITLE
Failed to load projection definition for: EPSG:32619

### ISSUE THREAD

**Issue by AntonioA-D-C** [proj4php/proj4php#138]
I have absolutely zero idea why this is happening, it was working just fine last week

 ```
 private function transformCoordinates($latitude, $longitude)
    {

        $proj4 = new Proj4php;
        $destinationProj = new Proj('EPSG:32618', $proj4);
        $sourceProj = new Proj('EPSG:4326' , $proj4);
        $point  = new Proj4phpPoint( $longitude, $latitude);


        $transformedPoint = $proj4->transform($sourceProj, $destinationProj, $point);

        $easting = $transformedPoint->x;
        $northing = $transformedPoint->y;

     
        return ['easting' => $easting, 'northing' => $northing];
    }

```
I just want to convert lat lng coordinates into easting and northing with a countries' projection

**Comment by mtiessen1175** [comment]
I also had trouble changing projections with EPSG catalogue codes just recently and think this has to do with a changed URL on _spatialreference.org_. See how the URL of your example EPSG:32618 (https://spatialreference.org/ref/epsg/32618/proj4.txt) differs from the URL in the corresponding proj4 [php file](https://github.com/proj4php/proj4php/blob/a6e6dd90f3c67da1db5bbe921a2a37b610f56ac5/src/Proj.php#L312), which would result in http://spatialreference.org/ref/epsg/32618/proj4/.

Hope this will help resolve the issue!
