### ISSUE TITLE
Projections for EPSG:3418 Iowa South are now inaccurate

### ISSUE THREAD

**Issue by jplhomer** [proj4php/proj4php#139]
Sometime in the last 30 days (maybe longer), the projections for epsg:3418 (Iowa South) are inaccurate:

- Here's an example of a coordinate in EPSG:3418: `1623863.8131117225, 643763.90620113909` 
- The expected WGS84 is: `lat: 41.766901, lng: -93.560676` 
- But today's result is: `lat: 44.960581, lng: -79.222403`

These calculations are performed using this project https://github.com/proj4php/proj4php which oddly hasn't seen any changes short of changing the URL on spatialreference.org to use a `.txt` suffix.

I'm noticing the incorrect results on https://epsg.io/3418-1696 are incorrect, too (the map shows the new incorrect bounds, which are in Canada instead of Iowa where they used to be). Apologies if this means it's not isolated to this repository, but I'm not sure exactly where to report this. Maybe EPSG.io is using repository, too?

Also wrote up some findings here: https://gis.stackexchange.com/questions/474573/projections-for-iowa-south-are-now-inaccurate-epsg-spatialreference

Thanks for your hard work on this project!

**Comment by nickolanack** [comment]
we should check to see if proj4js has this issue
