### ISSUE TITLE
Snyk xss vulnerability 

### ISSUE THREAD

**Issue by mitchhankins01** [proj4php/proj4php#141]
When running vulnerability testing using Snyk on the proj4php library, we are alerted of a high xss vulnerability in "WSProj4PHP_1.0.php" on line 89 and 97

according to Snyk: "Unsanitized input from an HTTP parameter flows into the echo statement, where it is used to render an HTML page returned to the user. This may result in a Cross-Site Scripting attack (XSS)."

Can you advise on whether this is truly a vulnerability? We are unable to modify the library due to the LGPL license.

Thank you!

**Comment by nickolanack** [comment]
Thank you for creating this. I will test to see if it is possible to execute xss attack with it. - At first glance I think it will throw an exception if invalid parameters are passed as url variables. In the meantime, I'll just delete the file and PR since it is not necessary to the functionality of the library

**Comment by mitchhankins01** [comment]
thank you @nickolanack, we will await your investigation

**Comment by nickolanack** [comment]
@mitchhankins01 
I removed the file WSProj4PHP_1.0.php and created release 2.0.16

If malicious url parameters are passed to the script an exception will be thrown before they are printed. However, the exception (if php errors are displayed) will also print the parameter with characters escaped for html, which would make it difficult to be used for xss. That said, the automatic escaping done by php error reporting is not meant to provide complete protection. 

Also, this vulnerability assumes that you have exposed this library to the web, and the file was accessible by a url, which is definitely not recommended.
