### ISSUE TITLE
PSR-4 autoloading (plus namespaces)

### ISSUE THREAD

**Issue by judgej** [proj4php/proj4php#2]
Is an autoloader something you will consider moving to? A PSR-4 autoloader is the way to go, with the composer autoloader being a good choice. All the `include()` statements would disappear immediately, and flexibility to extend the library in projects would increase.

I would also recommend the project is namespaced too, as that makes integration into projects immensely easier.

With PHP 5.4 ceasing even security updates at the end of this month, there is no real excuse to run this with PHP 5.2 compatibility (I would argue it is dangerous). However, now it is on github, there is no reason why a branch could not continue with legacy support for those that want it, while they work on upgrading, and the main branch becomes a namespacesed autoloading package.

I'm happy to help if the support to move that direction is there.

**Comment by julien2512** [comment]
You're welcome.

Dependency-injection is a well known pattern and I think it is a good idea to introduce it in proj4php. I saw jsor/proj4php start to add composer.json, that's a good starting point !

Proj4php5.2 branch is now on stage.

As I like to use the github maze, that is to make 2 branches :
1. upgrade php and introduce namespaces ;
2. adding composer ;

**Comment by julien2512** [comment]
Upgrade & proj4php namespace done (first release), and pulled on master.

Do you want to introduce composer ?

**Comment by judgej** [comment]
"introduce" as in make it work, or give you a summary about what it is and why you would use it?

**Comment by judgej** [comment]
Okay, [composer](https://getcomposer.org/) has the [PSR-4 autoloader](http://www.php-fig.org/psr/psr-4/) built in. There are other PSR-4 autoloaders out there, but the one in composer is handy and *just there* when you use composer.

It requires the files to be organised in a way so that it can find and load them. The directory structure follows (for the most part) the namespace path. More on this later.

composer is a dependency management tool. It is a zipped up PHP tool that is run from the command line like any other command tool. You tell it what PHP packages you want to use, and what versions, and it will go get them and also fetch any packages that those packages depend on. It does this using a *kind of magic* so you don't have to worry about anything being missing. Once installed, the package is immediately usable in your application through autoloading.

Now, composer picks up its packages by default from [packagist.com](http://packagist.com). That respository of packages can be kept automatically up-to-date from github using a hook, so that is one worry out of the way. Set up the hook, then every release you make through github is immediately added to packagist and everyone using your package will see it and be able to update.

**Comment by judgej** [comment]
Now, namespaces. The PSR-4 recommendation makes the top level of the namespace a *vendor* name. That's a project, an organisation, an individual - on a first-come, first-served basis. Your vendor would be "proj4php" since you already have it on github, assuming no-one has already taken it on packagist. The namespace would normally follow the same pattern, but use capitalised camel-case: *Proj4Php* - it's all convention, to create consistency between projects.

Under the vendor root, you can do what you like, but the convention is to make the second level the package or project name. This leaves room for other projects by the same vendor. So you have `Proj4Php` as the top level namespace in this case, but other projects could have a root namespace `Proj4Php\Whatever` and they won't clash. Everything in the project then goes under that.

The `vendor/project-name` (in lower case) is defined for composer, to identify the package and to help composer store it in the filesytem without clashing with other packages. In this case `proj4php/proj4php`.

Prefixes can be (should be) dropped from classes, as the namespace now projects them. Instead of class `proj4phpDatum` you now have class `Php4Proj\Datum` in `src/Datum.php` which composer will install in `vendors/proj4php/proj4php/`. To use that class in your proiject, do this:

~~~php
use Proj4Php\Datum; // At the top of the script

$datum = new Datum(...);
~~~

That's it - just use it, and the autoloader will find it and load it the first time it is used.

**Comment by judgej** [comment]
This project is already on packagist, and has had 4600+ downloads over the last few years. It is an exact mirror of the old sourceforge project:

https://github.com/jsor/proj4php

That is great for people wanting the legacy project. If this is going to move forward to use PSR-2/PSR-4/composer standards (and you might as well go all-out and do it properly) then it would be best to supply under the `proj4php` vendor name as it would be a new start to many. Keep the old version in a separate branch on github because with nearly 5000 downloads, it has quite a following, so there will be legacy systems out there.

**Comment by judgej** [comment]
You have a few branches already - it may be worth updating the `Readme.md` file for each to indicate what they are for, and where they are going.

**Comment by judgej** [comment]
Hope that helps explain how it all works, moving from a non-composer platform to composer plug a modern PSR approach. I can set up all the above for you in a branch. The "adding composer" bit does not need a branch of its own - it is just the additional of a single file along with the PHP, namespace and coding standard updates.

Which branch would you like me to do that in, and what is the minimum PHP version that is needed? I tend to go for PHP5.4 to cover most (safe and secure) hosting, although PHP 5.5+ does have some nice features. PHP5.5 is rarer, but I don't think there is anything fundamental in it that is really needed at this stage and can't be done in PHP5.4. So 5.4 is what I would recommend as a minimum, with compatibility up to 7.

**Comment by judgej** [comment]
How do you want me to manage pushes? I'm happy to push directly to a branch, but you would need to give permissions to the "Developpers" ([sic](http://www.urbandictionary.com/define.php?term=developers)) team to do this.

**Comment by julien2512** [comment]
lol, you are good judgej.

I've created a branch "adding-composer" because it's even faster to code than to talk about it.
Indeed, that's mean:
1. adding a composer file ;
2. change the README file ;
3. set off the "include" token in all files ;
...

Developper team got write access on the repo now.
"This team grants Write access: members can read from and push to the team’s repositories."

**Comment by judgej** [comment]
If I add composer.json to the master repository, I can get it linked to packagist.com. Then I can work on the further changes in branch. Would that be okay?

**Comment by julien2512** [comment]
yes !

**Comment by judgej** [comment]
Okay, get yourself an account on https://packagist.org/ and I'll add you as a maintainer.

**Comment by julien2512** [comment]
I am on packagist, and composer.json is up to date.

**Comment by judgej** [comment]
Okay, you are on, as a maintainer.

Clicking the `update` button here will scan the github repository and pull in any new releases that have been made. You can set up a hook in github so that it automatically notifies packagist of any new releases.

**Comment by judgej** [comment]
I'm also not entirely sure the sample code is working - I get this:

~~~text
Source :      2.3557811127971 48.831938054369 in L93
Conversion : 2.3557811127971 48.831938054369 in WGS84
~~~

and I'm not sure the lat/long coordinates should be the same for both?

**Comment by judgej** [comment]
Once happy that dev/master is working correctly, and still supports legacy applications, it may be a good time to pull it into the `php5.2` branch and make a release on that so that people can continue to use it. That branch can also accept bug fixes. It would be nice if everyone moved over to PHP5.4+composer, but with over 4000 users out there, I'm sure there will be all sorts of older applications that we probably don't want to break.

**Comment by judgej** [comment]
The projCode classes are now fully PSR-4 loaded, and do not instantiate themselves and add themselves to the global static arrays (a PSR-2 requirement: each file executes code *or* defines a class or function, but never both). The classes here have now lost their "Proj" prefix and filenames have been initial-capitalised to match the classname.

These classes are now instantiated in `Proj\loadProjCode()` and added to the global array there. When this array is no longer global, then there are far fewer places for it to be updated now.

**Comment by julien2512** [comment]
Great.
PHP 5.2 version will be proj4php 1.0.0 on packagist.

Your underdevelopment "composer" branch will be 2.0.0. When you're feeling ready (don't go too far away indeed !) pull request it so that I can check it a little.

Notice Winne27 joined the project, he used to work good when we were on sourceforge.

**Comment by judgej** [comment]
I'll aim to leave the composer branch in a working state at any time, and update the sample code to go with it, so feel free to pull from that branch to try it out at any time, no PR required.

I've been kind of tweaking it at the edges so far, putting PSR-4 autoloading in, making sure the scripts only *define* classes and don't instantiate them on loading, and replacing the defs code that execute and update globals with a simple `return` that returns data without changing anything. It's all about reducing side-effects.

The next stage will be focused on removing the static arrays, which are effectively the same as globals. That will involve a bit of DI so everything has access to the data as it is built up. A lot of the structure of the data has been inherited from the original JavaScript, which is a functional programming language that runs on a browser front end. This is an OO language that needs to run at the server back end alongside many more packages and probably a whole framework, so the problem needs to be tackled in a slightly different way.

**Comment by judgej** [comment]
I'll probably have a couple of hours I can put in every couple of days.

**Comment by julien2512** [comment]
First pull request done !

**Comment by judgej** [comment]
PSR-4 is done and working. Whether there still needs to be other namespace name changes or not, is something for future discussion. I'll close this issue in the meantime.

**Comment by julien2512** [comment]
Are you still working on adding-composer branch or do you need another one ?

**Comment by judgej** [comment]
Hmm, not sure - the scope is a lot more than just adding composer. I'll sleep on it tonight, and put forward a proposal tomorrow to see what you think. For me, making the Point (and Datum) into an immutable object would be a good thing to do next. It would have a knock-on effect across the module anywhere that the class(es) is used, but should simplify things in the long run.

It depends a lot also on how you want to manage this module in its various (incompatible) branches, and who the target audiences are. There will be people who used the old converted package that has been around for a couple of years on legacy projects. There will be people who want a version that is brought more up-to-date with composer. And then there are people who want to functionality but are starting afresh and just want to slip a package into their application that does things the modern PHP way without needing to be compatible with the Proj4JS approach (that's where I stand). All groups can be supported for a while, but they will diverge to a point where there is much less that can be shared between them.

**Comment by julien2512** [comment]
You are right. Proj4PHP is interesting because it is working as it is.

The key might be on autoload.php ... Is there's a way to include it on proj4php as a default version when composer is not present ?
May be composer project gives clues to that issue ? I am going to check that.

**Comment by judgej** [comment]
Any PSR-4 compliant autoloader will work. There are a number of them about, and they can be [just a few lines long](https://gist.github.com/mageekguy/8300961).

**Comment by julien2512** [comment]
That's a good idea.

I think we could see if 2.0.0 tag is download more or less than 1.0.0, and thus choose to set a default autoloader or not.

**Comment by julien2512** [comment]
You were right. Here is composer's support answer :
https://github.com/composer/composer/issues/4452
@jakoch tells me about the swiftmailer autoloader.

**Comment by judgej** [comment]
I think a lot of swiftmailer is still fairly old-style (it has been around for a long time) so the autoloader is not the simplest it could be. A PSR-4 autoloader for Prog3php would be very simple/very basic - PSR-4 autoloading is designed to make it easy by making sure the code structure follows strict rules.

**Comment by julien2512** [comment]
So 4 lines is enough to make autoload working !
These lines must be inside vendor/autoload.php to work.

Let's have a try with that configuration. I will use composer branch to do that.

**Comment by julien2512** [comment]
Done

**Comment by judgej** [comment]
Looks good. TBH, I'm not sure why DIRECTORY_SEPARATOR would be needed here, as "/" should work in all cases (on both Windows and *nix). I might ask on the fig forums whether I'm missing something here.

**Comment by judgej** [comment]
Also there is no significance with it being in a vendor directory within a package - just in the root of the project, without being in a directory, would be okay.

**Comment by julien2512** [comment]
You're welcome !
