### ISSUE TITLE
EPSG:3875

### ISSUE THREAD

**Issue by Linzdigr** [proj4php/proj4php#24]
Hi!

Not sure if it's an issue but one projection is named EPSG:3875, but I can't find any on spacialreference and google.
Is that it would not be EPSG:3857 instead (since it seems to have the same definition)?

**Comment by judgej** [comment]
* 3875 is "ETRS89 / GK21FIN" 2D Cartesian northing/easting from National Land Survey of Finland
* 3857 is "WGS 84 / Pseudo-Mercator" 2D Cartesian easting/northing

Does 3857 look closer to what you were expecting?

**Comment by gallab** [comment]
I think what Linzdigr mentionned is that  EPSG:3875 in this repo is matching EPSG:3857 definition. 

Judgej, according to https://epsg.io/3875 :
proj4.defs("EPSG:3875","+proj=tmerc +lat_0=0 +lon_0=21 +k=1 +x_0=21500000 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs");
In this repo there is not same def for 3875   :  

return [
    "+title= Google Mercator +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs",
];

**Comment by julien2512** [comment]
Thank you for your feedback !
