### ISSUE TITLE
Not able to show error when exceptions raised

### ISSUE THREAD

**Issue by sajin577** [proj4php/proj4php#28]
It is because of 
Proj4php.php -> transform method -> line 404:
 self::reportError("Proj4php initialization for: " . $source->srsCode . " not yet complete");

 $source->srsCode cannot be echoed because srsCode is projection, which is protected property in Point class.

**Comment by sajin577** [comment]
For re-creating the issue, try to convert a projection not already defined.

**Comment by julien2512** [comment]
Thank you. @coreation get it already but we did not pull request it as we were working on other issues. It is just to turn srcCode to public.
You shall pull request it if you really need to.

**Comment by coreation** [comment]
I think I'm running it fine now :), I got a list of supported projections, if any problems show up I know who to turn to and perhaps do a pull request myself ;)

**Comment by julien2512** [comment]
The pull request is done.
