### ISSUE TITLE
preojphp 5.2 inline projection or an example how to make it work with mga28355

### ISSUE THREAD

**Issue by camjo9999** [proj4php/proj4php#31]
Hi 

I am forced to use opensuse12.3 with php ver 5.3.17  [aaarrrrgh]

The code i have written in php for gps transformation in opensuse 13 works fine [php ver 5.6]

I need to go from Google maps to this
http://spatialreference.org/ref/epsg/gda94-mga-zone-55/

Any chance of some way to manually do this maybe?
Any change of inline transformation in 5.2 as there are no instructions for this.

If i run the same php file in opensuse 12.3  [php ver 5.3.17 ] i get this error

PHP Parse error:  syntax error, unexpected T_USE in /srv/www/htdocs/bc2fm/BC2FM_Main.php on line 110

Below is a segment of code that relates to this.

Note .... above here are just comments
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//SECTION: START
///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Proj4 is used for translating gps format to epsg format used here for fastmaps
106> $proj4ver="new";
107>
108> if ($proj4ver=="new"){
109> include(__DIR__ . "/proj4php-master/vendor/autoload.php");
110 > use proj4php\Proj4php;
111> use proj4php\Proj;
112> use proj4php\Point;

any help really appreciated
camjo

**Comment by judgej** [comment]
`__DIR__` is a PHP 5.3 thing (and was long overdue IMO).

The php 5.2 equivalent is `dirname(__FILE__)`

**Comment by judgej** [comment]
Personally I would not change the core of proj4php to fix this, but define `__DIR__` in your application instead:

~~~php
if (!defined(__DIR__)) define('__DIR__', dirname(__FILE__));
~~~

**Comment by julien2512** [comment]
judgej is right.

@camjo9999   you can also have a look to the test directory :  the unit test is also a good sample case.
It do not use autoload as in master branch.

**Comment by camjo9999** [comment]
Hi thanks for the replies

It seems the __dir__ is supported by 5.3.17 so the problem I am having seems to stem from somewhere else with the t_use error.

I did a strace to check , both attached for each version, one that worked one on 5.6 and one that didn't on php v5.3.17.

I tried upgrading to 5.6 on opensuse12.3 but i cant get it to work. [php5.6 supported on opensuse 13+ ]
I cant upgrade to oepnsuse 13+ due to another app compiled for that version. 
I will have to learn java and rewrite the other app to fix it [no source] or perl.
 
What is the quickest way forward

Can i edit the source direct? How could i do this for EPSG28355
http://spatialreference.org/ref/epsg/gda94-mga-zone-55/

I have burnt hours away , pressure is on now.

Is it possible to write my conversion of the GPS in javascript and embed it into the php?

Cam

[strace bad bc2fm proj4php.3.1.27.opensuse12.3.txt](https://github.com/proj4php/proj4php/files/160170/strace.bad.bc2fm.proj4php.3.1.27.opensuse12.3.txt)
[strace good bc2fm proj4php.56.opensuse13.2.txt](https://github.com/proj4php/proj4php/files/160171/strace.good.bc2fm.proj4php.56.opensuse13.2.txt)

**Comment by nickolanack** [comment]
my guess is that the error is because you have put your use proj4php\... statements inside a function, class, or class method. it needs to be outside of any of those.

**Comment by camjo9999** [comment]
Thanks nickolanack

I found that out yesterday and changed my code ,but I get the error now of 'nuthing'  , code just stops as per the trace files in post [2xback] . Damn ... thanks for the fix ,
it will help someone else with the T-Use error , which I wasted a full day on .

I am sure now its version non-capability , seems I am stuck now with writing something in perl or python to do the calculation and parse it back to php [running as a script/bash]  ....maybe

 Cheers
C

**Comment by julien2512** [comment]
There is now a travis unit test on proj4php5.2 branch for PHP 5.2 and PHP 5.3.
Both tests are working (usual projections tests).

The error might come from the gda94-mga-zone-55 projection.
