### ISSUE TITLE
Use of static globals throughout makes testing difficult

### ISSUE THREAD

**Issue by judgej** [proj4php/proj4php#4]
The use of static arrays in proj4php.php is effectively implementing globals for all data built up.

Some classes, when loaded, will instantiate themselves and add themselves to these globals.

Once of the rules of PSR-2 and PSR-4 is that a script should define a class, or execute code, but never both. Allt he scripts in projCode do both *and* mess around with the globals.

Let's work to getting rid of the globals and using DI throughout instead.

**Comment by judgej** [comment]
The scripts in the "defs" directory each add one or more definitions to the definition global.

Instead, they could return an array of definitions that is added to an array internal to the calling object. A method to set and get definitions on that object would allow external definitions to be added. So an application would add a custom definition more like this:

    $proj->addDefs(['MY DEF KEY' => 'My definition string']);

or

    $proj->addDef('MY DEF KEY', 'My definition string');

rather than adding an element to he global like this:

proj4php::$defs['MY DEF KEY'] = 'My definition string';

**Comment by judgej** [comment]
Here, all static functions and constants (where non-static methods and public properties) of the `Common` class are referenced directly to that class. Previously those values and methods were accessed in an instantiation of that class, and stored in a (global) static property of `Proj4php`. These are real statics (mainly simple mathematical utility functions) and constants, so with much fewer side-effects now.

Nothing should appear to work any differently, but it's a step forward.

**Comment by judgej** [comment]
The `Proj4php` object now has methods to add, get and check defs (`hasDef()`, `addDef()` and `getDef()`) so they are no longer global. All defs should still be loaded from the sources they have always been loaded from.

**Comment by julien2512** [comment]
Hi @judgej,
I guess you forget to close your issue, isn't it ? It seems you solve it by your own.
Or do you need some help on it ?
Happy New Year !

**Comment by judgej** [comment]
Happy New Year :-)

I think I got as far as I could with this one, without changing the structure more drastically. There are a lot of public properties set directly between the ProjCodes and the Points. Also still a lot of static methods in Common that are used by the ProjCodes, and which could be inherited from a class that all ProjCodes are derived. If that kind of thing is to be changed, then that would probably be better done under a separate ticket, so I think this can be closed.
