### ISSUE TITLE
How to use with only wkid

### ISSUE THREAD

**Issue by Jelle-S** [proj4php/proj4php#40]
I get data from a service which only tells me the wkid. I came across a case where the wkid is 102100. Which is basically ESRI:102100. I really have to mention that I'm not at home in the whole GIS/Geoservices world. But is it somehow possible to retrieve the right data with just the wkid? For example: EPSG:102100 does not exist (I know there's an equivalent, and that ESRI:102100 is deprecated, but I can't change the external service from where I get the data).

The other problem is that the definition for ESRI:102100 exists on http://spatialreference.org, but not where proj4php expects it to be. Proj4php looks for the definition on http://spatialreference.org/ref/esri/102100/ but it is actually found on http://spatialreference.org/ref/sr-org/6928/

Thanks in advance!

**Comment by julien2512** [comment]
ESRI:102100 seems to be set as an "authority" in ogc wkt :
`
PROJCS["WGS_1984_Web_Mercator_Auxiliary_Sphere",
    GEOGCS["GCS_WGS_1984",
        DATUM["D_WGS_1984",
            SPHEROID["WGS_1984",6378137.0,298.257223563]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Mercator_Auxiliary_Sphere"],
    PARAMETER["False_Easting",0.0],
    PARAMETER["False_Northing",0.0],
    PARAMETER["Central_Meridian",0.0],
    PARAMETER["Standard_Parallel_1",0.0],
    PARAMETER["Auxiliary_Sphere_Type",0.0],
    UNIT["Meter",1.0],
    AUTHORITY["ESRI","102100"]]
`

But I do not know any API to retrieve EPSG codes from authority one.

**Comment by julien2512** [comment]
Also, there are many others ESRI codes like
> ESRI:102091: Monte Mario Italy 1
> ESRI:102092: Monte Mario Italy 2
> ESRI:102101: NGO 1948 Norway Zone 1
> ESRI:102102: NGO 1948 Norway Zone 2

and a gap for ESRI:102100 ...

How many ESRI codes are left ?

**Comment by Jelle-S** [comment]
From what I understand, there are a lot of ESRI codes, but most of them have an EPSG alternative. The ArcGIS SOAP service has a method to retrieve the spacial reference by WKID. It could be an idea to implement a plugin of some sort that, if an ArcGIS SOAP service url is defined, and the format of the definition name is something like `WKID:102100`it does a SOAP call to that service to retreive it and use that. Unfortunately I currently don't think I have the time to implement that.

The ArcGIS SOAP service uses these authorities by default:

- A WKID in the EPSG code range (1000 - 32768) will result in an AUTHORITY name of "EPSG".
- A WKID in the ESRI code range (33000 - 199999) will result in an AUTHORITY name of "ESRI".
- A WKID in the user code range (200000 - 209199) will result in an AUTHORITY name of "CUSTOM".

See http://help.arcgis.com/en/arcgisserver/10.0/apis/soap/whnjs.htm#SOAP_Geometry_FindSRByWKID.htm for more info

**Comment by julien2512** [comment]
I get it.

I guess you telling me that there was an improvement in ESRI code that spatialreference.org do not take into account.
But Proj4php do not stand to replace spatialreference.org : there is only a method to overload some projection.

If you really want the ESRI:102100 to behave, you need to ask Howard Butler, Christopher Schmidt, Dane Springmeyer, or Josh Livni for it.
(http://spatialreference.org/about/)
Indeed, I can try to ask it for you if you really need to.

But, if you want WKID to be an alias for ESRI reference in proj4php, you will need to pull request it by yourself. As there is no such way, it might be accepted.

**Comment by julien2512** [comment]
Alright @Jelle-S, I finally found your drupal extension for proj4php !

So, you need to use proj4php as a drupal webservice extension.
That's a good idea.

But, I am back to my first proposals :
1. change spatialreference.org 
or
2. manually set the missing ESRI codes in proj4php defs directory ;

I am adding ESRI:102100 now.

**Comment by julien2512** [comment]
@Jelle-S  Is it possible to close that issue one year ago ?

**Comment by Jelle-S** [comment]
Hi, sorry, yes I'll close it. In the end the customer didn't need this anymore due to budget cuts if I remember correctly. Thanks for your help though!
