### ISSUE TITLE
Undefined index: gauss

### ISSUE THREAD

**Issue by DualCore** [proj4php/proj4php#42]
There is a problem in the Sterea.php file on line 91
`Undefined index: gauss in .... proj4pgp\projCode\Sterea.php on line 91`.

The problem is already fixed in the forward part by changing:
`$p = Proj4php::$proj['gauss']->forward($p);` into:
`$p = parent::forward($p);`

This should also be done in the inverse method by changing:
`$p = Proj4php::$proj['gauss']->inverse($p);` into:
`$p = parent::inverse($p);`

The problem comes up when changing EPSG:28992 to EPSG:4326.

**Comment by julien2512** [comment]
Thank you @DualCore, your commit.
