### ISSUE TITLE
Coordinates shown on map are slightly off

### ISSUE THREAD

**Issue by Agilix** [proj4php/proj4php#46]
We have a crud where users can add lon,lat values to a object.
Next we converse these onto a map with certain dimensions. But the coordinates seems off on the map.
What should be mainland Brasil is at the coast. Europe seems slight off as well.

Now I got this from a previous developer so I'm not totally on board on what he did, i.e. the mapping.

`/**
     * Get map data for template
     *
     * @return ArrayList
     */
    public function getMapData($mapWidthPx, $mapHeightPx, $dotSize)
    {
        $data = [];

        $proj4 = new Proj4php();
        $source = new Proj('EPSG:4326', $proj4); // http://spatialreference.org/ref/epsg/4326/
        $dest = new Proj('EPSG:3785', $proj4); // http://spatialreference.org/ref/epsg/3785/

        // Boundary of the destination: http://spatialreference.org/ref/epsg/3785/
        $mapBoundary = [
            ['-180', '-85'],
            ['180', '-85']
        ];

        $pointSrc = new Point($mapBoundary[0][0], $mapBoundary[0][1], $source);
        $mapBoundaryPoint = $proj4->transform($dest, $pointSrc);

        foreach ($this->Coordinates->getValue() as $val) {
            list($lat, $lon) = explode(',', $val);
            $pointSrc = new Point($lon, $lat, $source);
            $pointDest = $proj4->transform($dest, $pointSrc);

            $data[] = ArrayData::create([
                'X' => ($mapWidthPx/($mapBoundaryPoint->x*2)) * ($pointDest->x + $mapBoundaryPoint->x) - ($dotSize/2),
                'Y' => ($mapHeightPx/($mapBoundaryPoint->y*2)) * ($pointDest->y + $mapBoundaryPoint->y) - ($dotSize/2)
            ]);
        }

        return ArrayList::create($data);
    }`

Anyone by chance see why it isn't showing completely on point?

**Comment by Agilix** [comment]
Could it be the image of the map that is wrong?

![worldmap](https://cloud.githubusercontent.com/assets/1481082/15574614/bf57a878-234e-11e6-9fce-471b11222a3a.png)

**Comment by julien2512** [comment]
I guess your map projection is EPSG 3785 and the script try to interpolate coordinates with the map boundaries. The image seems to fit with the EPSG 3785 boundaries.

So your need is to translate from a point to a pixel. Let me think about it.

**Comment by julien2512** [comment]
Assuming (0,0) is the bottom left of your image, you can try
```
$data[] = ArrayData::create([
            'X' =>($pointDest->x - $mapBoundaryPoint->x)/$dotSizeX,
            'Y' =>($pointDest->y - $mapBoundaryPoint->y)/$dotSizeY
]);
```

and I think $dotSize is somethink like
`
$dotSizeX = abs($mapBoundaryPoint->x - $secondMapBoundaryPoint->x)/$mapWidthPx;
$dotSizeY = abs($mapBoundaryPoint->y - $secondMapBoundaryPoint->y)/$mapWidthPy;
`
and you need the second boundary Point for that.

**Comment by Agilix** [comment]
@julien2512 The map is indeed a EPSG:3758 display.
The dotSize is a width that we give to the function to tell it what size the dot will be (in px) on the map.
That is why we substract half of it's size of the coordinate so that the center of the dot is on the location.

**Comment by julien2512** [comment]
if X and Y are in pixels, you can't substract it by dotSize that is in meters.

**Comment by Agilix** [comment]
Fixed it, it was indeed with the dotSize. Thank you for the help @julien2512

**Comment by julien2512** [comment]
Yes it was ! Thanks for using proj4.
