### ISSUE TITLE
Wrong results in converting from EPSG:3003 to EPSG:32632

### ISSUE THREAD

**Issue by ariaveta** [proj4php/proj4php#66]
Hello I have problems in converting data from EPSG:3003 to EPSG:32632 using proj4php.

$proj4 = new Proj4php();
$proj3003 = new Proj('EPSG:3003', $proj4);
$proj32632 = new Proj('EPSG:32632', $proj4);
$pointSrc = new Point(1604272, 4875650, $proj3003);
$pointDest = $proj4->transform($proj32632, $pointSrc);

Results:
604268.62254309 4875469.4150243 (wrong)

Expected results (calculated though cs2cs and other, see below )
604242.97	4875633.36

Differences: 
-25 163

I also tried to add projections definitions by hands but I get same results and I cannot figure out why.
Any hint? Thanks.

---
Conversion made by cs2cs:
echo "1604272 4875650" | cs2cs +init=epsg:3003 +to +init=epsg:32632
604242.97	4875633.36 (correct)

**Comment by ariaveta** [comment]
I solved, I used wrong definitions for EPSG:3003. 
I first used the default definitions, then the ones provided from spatialreference.org with same (wrong) results.
I then tried to use defs from epsg.io and I got correct results.

Thanks

**Comment by julien2512** [comment]
Yes, there is no more update on spatialreference.org for years.

There is only a big lack on proj4php : nadgrid support. Your usecase (TMerc to WGS) is fully supported.
