### ISSUE TITLE
Conversion wrong when using esriwkt string

### ISSUE THREAD

**Issue by rrushton** [proj4php/proj4php#67]
```php
$proj4 = new \proj4php\Proj4php();
$proj4required = new \proj4php\Proj('EPSG:4326', $proj4);

$prj = 'PROJCS["OSGB 1936 / British National Grid",GEOGCS["OSGB 1936",DATUM["D_OSGB_1936",SPHEROID["Airy_1830",6377563.396,299.3249646]],PRIMEM["Greenwich",0],UNIT["Degree",0.017453292519943295]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",49],PARAMETER["central_meridian",-2],PARAMETER["scale_factor",0.9996012717],PARAMETER["false_easting",400000],PARAMETER["false_northing",-100000],UNIT["Meter",1]]';

/** THIS ONE WORKS 
$prj = '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs';
**/ 

$proj4current = new \proj4php\Proj($prj, $proj4);

$point = [
    'y' => 175166.25201076,
    'x' => 518060.14114953, 
];

$pointSrc = new \proj4php\Point($point['x'], $point['y'], $proj4current);
$pointDest = $proj4->transform($proj4required, $pointSrc);
```
$pointSrc is 518060.14114953 175166.25201076
$pointDest is 5.2856187226434 50.347691102477 but should be -0.30191227791194 51.463165234511

The $prj is take from http://spatialreference.org/ref/epsg/27700/esriwkt/
The commented out "THIS WORKS" $prj is also taken from http://spatialreference.org/ref/epsg/27700/proj4/ and works correctly.

Not sure if I am missing something obvious.

**Comment by julien2512** [comment]
Hi @rrushton,

It's been a long time since the last issue !

I am going to check that tonight.

Regards
Julien.

**Comment by julien2512** [comment]
I think it comes from the spheroid. I need to check it further up !

**Comment by julien2512** [comment]
That is not the spheroid.

from wht
`x=-0.30191231941096,y=51.463165234294`

from inline :
`x=-0.30032745289154,y=51.463338091149`

entering debug mode

**Comment by julien2512** [comment]
From wkt :
```
transform point 518060.14114953,175166.25201076
from 
to EPSG:4326
convert to_meter => 518060.14114953,175166.25201076
inverse => -0.0052417028849581,0.89819272742443
geodetic_to_geocentric(-0.0052417028849581,0.89819272742443)
Datum code=OSGB36
Datum type:2
a=6377563.396
b=6356256.91
es=0.0066705397615973
Param 0=446.448
Param 1=-125.157
Param 2=542.06
Param 3=7.2819014902652E-7
Param 4=1.1974897923406E-6
Param 5=4.0826160086234E-6
Param 6=0.9999795106
geocentric_to_wgs84(3981457.6168002,-20869.809012462)
Dx=446.448
Dy=-125.157
Dz=542.06
Rx=7.2819014902652E-7
Ry=1.1974897923406E-6
Rz=4.0826160086234E-6
M=0.9999795106
geocentric_to_geodetic(3981828.5182313,-20981.898148084)
Datum code=WGS84
Datum type:4
a=6378137
b=6356752.3142452
es=0.0066943799901411
Param 0=0
Param 1=0
Param 2=0
datum_transform => -0.005269364026054,0.89820167683631
convert to longlat => -0.30191231941096,51.463165234294
Transform result -0.30191231941096 51.463165234294
string(37) "x=-0.30191231941096,y=51.463165234294"
```

From inline:
```
transform point 518060.14114953,175166.25201076
from OSGB 1936 / British National Grid
to EPSG:4326
convert to_meter => 518060.14114953,175166.25201076
inverse => -0.0052417028870856,0.89819272742564
from_greenwich => -0.0052417028870856,0.89819272742564
geodetic_to_geocentric(-0.0052417028870856,0.89819272742564)
Datum type:4
a=6377563.396
b=6356256.9092373
es=0.0066705399999852
no params
geocentric_to_geodetic(3981457.6170856,-20869.809022429)
Datum code=WGS84
Datum type:4
a=6378137
b=6356752.3142452
es=0.0066943799901411
Param 0=0
Param 1=0
Param 2=0
datum_transform => -0.0052417028870856,0.89820469375757
convert to longlat => -0.30032745289154,51.463338091149
Transform result -0.30032745289154 51.463338091149
string(37) "x=-0.30032745289154,y=51.463338091149"
```

These are obviously not the same !

**Comment by julien2512** [comment]
Many differences between the inline and wkt projections :

inline :
`"title : projName :tmerc units :Meter datum_params : datumCode : axis :enu x0 :400000 y0 :-100000 localCS : srsCode :OSGB 1936 / British National Grid R_A : a2 :40673314869999 a :6377563.396 alpha : b2 :40402001896227 b :6356256.9092373 datumName :D_OSGB_1936 defData: e :0.081673373874141 ellps :Airy_1830 ep2 :0.0067153349101164 es :0.0066705399999852 from_greenwich :0 k0 :0.9996012717 lat0 :0.85521133347722 lat1 : lat2 : lat_ts : long0 :-0.034906585039887 longc :-0.034906585039887 na"`
`

wkt :
`"title : projName :tmerc units :m datum_params :Array datumCode :OSGB36 axis :enu x0 :400000 y0 :-100000 localCS : srsCode :EPSG:27700 R_A : a2 :40673314869999 a :6377563.396 alpha : b2 :40402001905923 b :6356256.91 datumName :Airy 1830 defData:+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +datum=OSGB36 +units=m +no_defs e :0.081673372414743 ellps :airy ep2 :0.0067153346685161 es :0.0066705397615973 from_greenwich : k0 :0.9996012717 lat0 :0.8552113334"`
`

**Comment by rrushton** [comment]
@julien2512 thanks for looking into this. Just curious if you got any farther in figuring out the issue because I am at a loss :) Thanks again.

**Comment by julien2512** [comment]
It seems some figured it out without fixing ! (as the unit test was wrong to pass it through).

I need to seek a bit more into the WKT parser. May be other projections are issued too.

**Comment by julien2512** [comment]
@rrushton A little more days to wait before I tryed to fix it ! I do not have my laptop right now :)

**Comment by julien2512** [comment]
The datum_type is not correct in the wkt release. So geocentric_to_wgs84 is not applied.

**Comment by julien2512** [comment]
The datumCode D_OSGB_1936 was not known by Wkt.php, but OSGB 1936 was.
So one was working, the other not.
And also, there is no way to add a new datum Code by your own !

I have add D_OSGB_1936 to the list.
