### ISSUE TITLE
Use DI where appropriate

### ISSUE THREAD

**Issue by judgej** [proj4php/proj4php#7]
The sample code shows $proj (`\proj4php\Proj4php`) being passed into `\proj4php\Proj` when it is instantiated. However, that parameter is not defined nor used in the constructor for `\proj4php\Proj`. It appears to be a left-over from the JS source project.

Just *instantiating* `\proj4php\Proj4php` sets up the globals and those are referenced directly from `\proj4php\Proj`.

This constructor parameter could be added, with `\proj4php\Proj4php` injected and that injected version used instead of the static globals.

**Comment by judgej** [comment]
There is some magic happening with the dependencies of the projections - some projects need dependent projections created first, then initialised, then properties copied over. Need to look at what is actually happening here in some more detail, since the static globals are confusing things a lot. I suspect a bit of DI may help with the dependencies.

**Comment by winne27** [comment]
There is only one projection depending on another projection:
sterea which depends on gauss

I think a better solution is to define the projection as an extension like this
```PHP
class Proj4phpProjSterea extends class Proj4phpProjGauss
{
   ...
}
```
So also can get rid of the terrible code
```PHP
if( false !== ($dependsOn = isset($this->projection->dependsOn) && !empty($this->projection->dependsOn) ? $this->projection->dependsOn : false) )
{
      Proj4php::extend( Proj4php::$proj[$dependsOn], $this->projection);
      Proj4php::$proj[$dependsOn]->init();
      Proj4php::extend( $this->projection, Proj4php::$proj[$dependsOn] );
}
```
in function initTransforms() in file proj4phpProj.php at line 288, because this block then is not neccessary anymore.

**Comment by judgej** [comment]
If it's as simple as that, it will be a pleasure. That block of code is the thing that threw me - I did not understand it.

I think this comes from the JS source, where each class is loaded from a URL and then "joined together" at the front end in the browser. Since all the classes are there in the package, and can simply extend each other without the need to fetch them via URLs, then it makes sense doing it by extending classes.

**Comment by winne27** [comment]
Furthermore the public function loadProjCodeSuccess( $projName ) in line 248 in   proj4phpProj.php could  be deleted and the function call in line 236 should be replaced by

```PHP
$this->initTransforms();
```

The mechanism with $dependsOn is not more then an confusing workarround for a class extension and you are right this comes from the JS source. But I think in Javascript also better solutions are possible.

**Comment by judgej** [comment]
So a question: when you create a projection you give it an SRS Code:

    $projection = new Proj('EPSG:2154');

That code looks up a `def` and that `def` also points to a projection code object, which is loaded into the projection.

The more I look at this, the more I wonder whether the projection classes should be an extension of the `Proj` class. Instead you would have a factory method that returns the projection:

    $projection = Proj::instance('EPSG:2154');

This would parse enough of the SRS Code to determine which projection to instantiate, which it would, passing it further data to parse and finish initialising itself.

Does that make sense, or am I missing something about the way these projections work?

If there are external projection classes, then they could either extend `Proj` directly, or be injected into an interface class that extends `Proj` and uses the external class using its own API.

**Comment by julien2512** [comment]
It seems to come from javascript logic.
A factory pattern is far much better !

But actually, new Proj() syntax is an easiest way to define projections.
We may implement both logics and tag the older one "deprecated" ?

**Comment by julien2512** [comment]
That issue appears to be closed too. @judgej, can I close it ?

**Comment by judgej** [comment]
I'll beat you to it!
