### ISSUE TITLE
Incorrect transformation, from EPSG:4326 to EPSG:2274

### ISSUE THREAD

**Issue by dlynnsmith** [proj4php/proj4php#72]
I am getting very wrong results with this conversion. 
Long/Lat of -85.30737679999999,35.0435959
Should return 2175838.59428;259279.53508
Does return 677630.12892331;92267.825943254

I am using the default projection for EPSG:4326.  The projection I have defined for EPSG:2274 is "+proj=lcc +lat_1=36.41666666666666 +lat_2=35.25 +lat_0=34.33333333333334 +lon_0=-86 +x_0=600000 +y_0=0 +datum=NAD83 +units=us-ft +no_defs".

This website gives the expected result: https://mygeodata.cloud/cs2cs/

That result is successful when passed to a local ArcGIS REST service: The "Identify" function returns the layers needed.  The proj4js script also returns correct results.

My code is:
		// Now look for the Council District (Convert lat/long to County's coordinate system, call to them, and parse the response)
		$proj4 = new Proj4php();

		// Now get the Council District
		// Convert lat/lng from Google to Hamilton County coordinate system
		$proj4->addDef("EPSG:2274",'+proj=lcc +lat_1=36.41666666666666 +lat_2=35.25 +lat_0=34.33333333333334 +lon_0=-86 +x_0=600000 +y_0=0 +datum=NAD83 +units=us-ft +no_defs');
		$googleCoordinates = new Proj( 'EPSG:4326', $proj4 ); // WGS 84 (EPSG:4326)
		$countyCoordinates = new Proj( 'EPSG:2274', $proj4 ); // NAD83 / Tennessee (ftUS) (EPSG:2274)
		$oldX = $geoloc['results'][0]['geometry']['location']['lng'];
		$oldY = $geoloc['results'][0]['geometry']['location']['lat'];
		$oldCoordinates    = new Point( $oldX, $oldY, $googleCoordinates );
		$newCoordinates    = $proj4->transform( $countyCoordinates, $oldCoordinates );
		$newX = $newCoordinates->x;
		$newY = $newCoordinates->y;

**Comment by julien2512** [comment]
I have never ended the nadgrid transformation as in #53.

**Comment by dlynnsmith** [comment]
Duplicate of NAD27 to WGS84/NAD83 does not calculate correctly #53
